artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion/raw
  source_URL: https://drive.google.com/file/d/13k9Yl1msxVidNneWm8XJXG__XRUWQBno/view?usp=sharing
  local_data_file: artifacts/data_ingestion/raw/data.csv
  unzip_dir: artifacts/data_ingestion
