artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/13k9Yl1msxVidNneWm8XJXG__XRUWQBno/view?usp=sharing
  local_data_file: artifacts/data_ingestion/reddit.csv
  

data_validation:
  DATA_VALIDATION_DIR: artifacts/data_validation
  train_file_path: artifacts/data_validation/training_data.csv
  test_file_path: artifacts/data_validation/test_data.csv
  drift_report_file_path: artifacts/data_validation/drift_report.json
  validation_status_file: artifacts/data_validation/data_validation_artifact.json
  
data_Transformation:  
  DATA_transformation_DIR: artifacts/data_Transformation
  transform_train_file: artifacts/data_Transformation/train/transform_training_data.csv
  transform_test_file: artifacts/data_Transformation/test/transform_test_file.csv
  x_train_file_path: artifacts/data_Transformation/train/x_train.npz
  y_train_file_path: artifacts/data_Transformation/train/y_train.csv
  transformer: artifacts/data_Transformation/transformer.pkl


prepare_model:
    root_dir: artifacts/prepare_base_model
    trained_model_path: artifacts/prepare_base_model/trained_model.pkl
    